### ISSUE TITLE
It's not working (FW 3.60 with HENkaku Ensō)

### ISSUE THREAD

**Issue by Midori7** [usineur/openjazz#3]
Like in a title. When I try open game, then it back me to the menu.

**Comment by usineur** [comment]
Copy datafiles to ux0:data/jazz
Copy openjazz.000 to ux0:data/jazz

**Comment by Midori7** [comment]
I didn't have _"jazz"_ folder in _"data"_, so i created (if it matters). But anyway... it still not working.

**Comment by usineur** [comment]
Just by curiosity... Can you list me the content of your "_jazz_" folder ?

**Comment by Midori7** [comment]
"openjazz.000"
"res" folder
"src" folder
and i put inside .vpk content. So basically everything what I would.

**Comment by usineur** [comment]
???

Instructions are given here: 
https://github.com/usineur/openjazz/releases

Datafiles **must** have to be placed into **ux0:data/jazz/**
The vpk is not designed to be modified manually or whatever.

**Comment by Midori7** [comment]
Sorry for my ignorance (that I didn't read the text properly).. Thanks a lot.
